* README (REQUIREMENTS): Note that Python 2.1 or higher 	is required. 	* README.sources: Remove restriction that software must work with 	Python 1.5. 	* configure.in: Check for Python 2.1 or higher. 	* configure: Regenerated. 	* qm/qm.sh (QM_PYTHON_FLAGS): New variable. 	(qm_python): Check /usr/bin/python2 before falling back to 	the python in the PATH. 	* qm/queue.py: Fix copyright notice. 	* qm/setup_path.py.in: Issue an error if an old version of 	Python is in use. 	* qm/trace.py: New file. 	* qm/test/cmdline.py (QMTest.__init__): Create a trace object. 	(QMTest.GetTracer): Return it. 	* qm/test/commnd_thread.py: Fix copyright notice. 	* qm/test/execution_engine.py: Likewise. 	(ExecutionEngine): Add trace message throughout. 	(ExecutionEngine._Trace): New method. 	* qm/test/target.py (Target.RunTest): Remove unnecessary code. 	* qm/test/doc/reference.xml: Update description of how QMTest 	locates the python interpreter to use.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -823,8 +823,8 @@ echo "Cannot find Python interpreter $PYTHON."; exit 1
 fi
 
 else
-  # Extract the first word of "python", so it can be a program name with args.
-set dummy python; ac_word=$2
+  # Extract the first word of "python2 python", so it can be a program name with args.
+set dummy python2 python; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
 echo "configure:830: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PYTHON'+set}'`\" = set"; then
@@ -864,18 +864,27 @@ fi
 
 echo $ac_n "checking Python version""... $ac_c" 1>&6
 echo "configure:867: checking Python version" >&5
-PYTHON_VERSION=`$PYTHON -c "import sys; import string; print string.split(sys.version, ' ')[0][:3]"`
+PYTHON_MAJOR=`$PYTHON -c "import sys; import string; print string.split(sys.version, '.')[0]"`
+PYTHON_MINOR=`$PYTHON -c "import sys; import string; print string.split(sys.version, '.')[1]"`
+PYTHON_VERSION="${PYTHON_MAJOR}.${PYTHON_MINOR}"
 echo "$ac_t""$PYTHON_VERSION" 1>&6
 
 
+# Some Python versions before 2.1 have serious bugs if threads and
+# fork are used together.  Therefore, Python 2.1 or higher is required.
+if test "$PYTHON_MAJOR" -lt 2 || \
+   (test "$PYTHON_MAJOR" -eq 2 && test "$PYTHON_MINOR" -lt 1); then
+  { echo "configure: error: QM requires Python version 2.1 or greater" 1>&2; exit 1; }
+fi
+
 echo $ac_n "checking Python prefix""... $ac_c" 1>&6
-echo "configure:873: checking Python prefix" >&5
+echo "configure:882: checking Python prefix" >&5
 PYTHON_PREFIX=`$PYTHON -c "import sys; print sys.prefix"`
 echo "$ac_t""$PYTHON_PREFIX" 1>&6
 
 
 echo $ac_n "checking Python platform""... $ac_c" 1>&6
-echo "configure:879: checking Python platform" >&5
+echo "configure:888: checking Python platform" >&5
 PYTHON_PLATFORM=`$PYTHON -c "import distutils.util; print distutils.util.get_platform()" 2>/dev/null`
 if test $? -ne 0; then
   echo "$ac_t""could not be determined" 1>&6
@@ -888,7 +897,7 @@ echo "$ac_t""$PYTHON_PLATFORM" 1>&6
 # Extract the first word of "happydoc", so it can be a program name with args.
 set dummy happydoc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:892: checking for $ac_word" >&5
+echo "configure:901: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_HAPPYDOC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -926,7 +935,7 @@ fi
 # Extract the first word of "jade", so it can be a program name with args.
 set dummy jade; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:930: checking for $ac_word" >&5
+echo "configure:939: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JADE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -962,7 +971,7 @@ fi
 # Extract the first word of "tidy", so it can be a program name with args.
 set dummy tidy; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:966: checking for $ac_word" >&5
+echo "configure:975: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_TIDY'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -999,7 +1008,7 @@ fi
 
 if test "$JADE" != no; then
   echo $ac_n "checking xml.dcl""... $ac_c" 1>&6
-echo "configure:1003: checking xml.dcl" >&5
+echo "configure:1012: checking xml.dcl" >&5
   XML_DCL=no
   for file in \
     /usr/share/doc/jade*/pubtext/xml.dcl \
@@ -1018,7 +1027,7 @@ fi
 
 
 echo $ac_n "checking DocBook stylesheets""... $ac_c" 1>&6
-echo "configure:1022: checking DocBook stylesheets" >&5
+echo "configure:1031: checking DocBook stylesheets" >&5
 DOCBOOK_STYLESHEETS=no
 for dir in \
   /usr/lib/sgml/stylesheets/docbook \
@@ -1035,7 +1044,7 @@ echo "$ac_t""$DOCBOOK_STYLESHEETS" 1>&6
 
 DOCBOOK_DTD=
 echo $ac_n "checking for docbook DTD""... $ac_c" 1>&6
-echo "configure:1039: checking for docbook DTD" >&5
+echo "configure:1048: checking for docbook DTD" >&5
 # Check whether --with-docbook-dtd or --without-docbook-dtd was given.
 if test "${with_docbook_dtd+set}" = set; then
   withval="$with_docbook_dtd"
